interface ILinkRegistration extends HTMLElement {
  _init(),
  _initUsableCbks(),
  _initAttributesMgmt(),
  _approximateBezierTime(mousPos :IDot) :number,
  displayDotMoveIndics(dotIdx :number) :void,
  hideDotMoveIndics(dotIdx :number) :void,
  displayCtrlMoveIndics() :void,
  hideCtrlMoveIndics() :void,
  _startCtrlMoving(evt :any) :void,
  _stopCtrlMoving() :void,
  _ctrlMove(evt) :void,
  _startDotMoving(dotIdx :number) :void,
  _stopDotMoving(dotIdx :number) :void,
  _dotMove(dotIdx :number, evt) :void,
  _computePosWGrMap(dotIdx :number, potentialDot :IDot) :IDot,
  _setVisibilityOfHandyDots(dotIdx :number, visible :boolean) :void,
  _computePosWoGrMap(dotIdx :number, potentialDot :IDot) :IDot,
  repaint() :void,
  _repaint() :void,
  _setVisibilityOfControlDot(visible :boolean) :void,
  _addElementToNestedSvg() :void,
  _svgSrc :string,
  createdCallback(),
  attachedCallback(),
  detachedCallback(),
  attributeChangedCallback(attrName :string),
  _computeLength(dot1 :IDot, dot2 :IDot) :number,
  _domIdInSvg :number,
  initNestedSvg(),
  _initPotentialGravityMap(),
  refreshInnerSvg() :void,
  _initDomElts() :void,
  _initListeners() :void,
  _removeListeners() :void
}
